overrides:
  "vue": "beta"
  "@vue/compiler-core": "beta"
  "@vue/compiler-dom": "beta"
  "@vue/compiler-sfc": "beta"
  "@vue/compiler-ssr": "beta"
  "@vue/compiler-vapor": "beta"
  "@vue/reactivity": "beta"
  "@vue/runtime-core": "beta"
  "@vue/runtime-dom": "beta"
  "@vue/runtime-vapor": "beta"
  "@vue/server-renderer": "beta"
  "@vue/shared": "beta"
  "@vue/compat": "beta"
  vite: "catalog:"

peerDependencyRules:
  allowAny:
    - "vue"
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@^0.2.4
  vite-plus: ^0.2.4
minimumReleaseAgeExclude:
  - vue-router@5.2.0
